### ISSUE TITLE
Shoot Control can not set fric_wheel_spd

### ISSUE THREAD

**Issue by lyziew** [RoboMaster/RoboRTS#11]
when i set   fric_wheel_spd = 1, is ok the wheel run well, but when i set "fric_wheel_spd" more then one , the wheel did not run, is there a shoot control sample or is there some wrong with the RoboRTS-Firmware

**Comment by KevinLADLee** [comment]
I think it is a problem on embedded layer. Please open an issue in [RoboRTS-Firmware](https://github.com/RoboMaster/RoboRTS-Firmware) repo.
