### ISSUE TITLE
Robot cannot follow the yaw angle specified by the goal

### ISSUE THREAD

**Issue by dongleecsu** [RoboMaster/RoboRTS#13]
In the newest RoboRTS code(commit 9093c2b9255ac968d96d6c45d87344a978826bff), no matter what the yaw angle of the goal is, the direction of the robot (red axes in rviz) always points to the right (says even the goal direction points to the left). \
**NOTE:** the only change to the code is that `yaw_goal_tolerance` is set to 0.1 instead of 3.14, which should make sense since we want to follow the goal direction.

**Comment by XYvven** [comment]
we will fix this issue in next commit

**Comment by dongleecsu** [comment]
Thanks, fixed
