### ISSUE TITLE
it seem that there is something wrong with the new version of  serial_com_node

### ISSUE THREAD

**Issue by lyziew** [RoboMaster/RoboRTS#16]
after update the code
i found my tx2 con not communicate with rm board

**Comment by ZhangPeike** [comment]
It is tested that the TX2 serial port messed up data if baudrate is bigger than 460800, it is recommended to use serial-usb converting module, or tune the baudrate on both ports.
Maybe "serial_port" in the configuration file in /modules/driver/serial/config is wrong, check your serial port name and correct.

**Comment by ZhangPeike** [comment]
Could you show the running result and which error it reported?

**Comment by KevinLADLee** [comment]
No details of issue. Please reopen this issue if you still have problems.
