### ISSUE TITLE
We cannot send chassis control to rm board.

### ISSUE THREAD

**Issue by Robin970822** [RoboMaster/RoboRTS#17]
We review the code in serial_com_node and find this.
https://github.com/RoboMaster/RoboRTS/blob/197881b722790d0c371ff719e771512797057df6/modules/driver/serial/serial_com_node.cpp#L506
This pack_length_equals 0 all the time. Are you sure, here is not pack_length?

**Comment by ZhangPeike** [comment]
Yes, the variable should be pack_length instead of pack_length_.

**Comment by Mor-harry** [comment]
确实有问题，请检查代码，谢谢
