### ISSUE TITLE
Local planner robot footprint model wrong?

### ISSUE THREAD

**Issue by dongleecsu** [RoboMaster/RoboRTS#19]
In the `timed_elastic_band.prototxt`, the robot footprint is set to `POLYGON`. But when setting the footprint model in function `RobotFootprintModelPtr()`, it actually return the `PointRobotFootprint` model [here](https://github.com/RoboMaster/RoboRTS/blob/master/modules/planning/local_planner/robot_position_cost.h#L146). Since the teb code in RoboRTS is significantly different from the ros teb source code, does this wrong model setting affect the local planning?

**Comment by XYvven** [comment]
I am sorry, and I will fix this bug in next commit
