### ISSUE TITLE
messages/localization.h

### ISSUE THREAD

**Issue by joke123kobe** [RoboMaster/RoboRTS#2]
when I tried to compile the project,it warned me that :message/localization.h .no such file or directory.
It's a header files in modules/perception/localization/localization_client.cpp.Is it a ros header file cause I can't find it in ros libraries.I use ros kinetic by the way

**Comment by KevinLADLee** [comment]
You could try following steps to fix it. We will fix this issue in next commit.
```shell
cmake ..
make messages_generate_messages
make -j4
```
