### ISSUE TITLE
We cannot receive data from uwb normally

### ISSUE THREAD

**Issue by Robin970822** [RoboMaster/RoboRTS#20]
We review RoboRTS and RoboRTS-Firmware again and find
https://github.com/RoboMaster/RoboRTS/blob/98a2ff1e297ba57e51ca46e72892c98a6fb0f99c/modules/driver/serial/infantry_info.h#L47
https://github.com/RoboMaster/RoboRTS-Firmware/blob/14dfbf5add4c691b335f3c06a89d6c18e8c051dd/MDK-ARM/rmlib/judgement_info.h#L46
They are different.

**Comment by KevinLADLee** [comment]
Yep, the communication protocol has been updated in RoboRTS-Firmware. We will update in this repo soon, but you could also change your code in serial module first. 
Reference:
[New protocol](https://github.com/RoboMaster/RoboRTS-Firmware/blob/master/Doc/protocol/readme.md)
