### ISSUE TITLE
Difference on Shoot Control between RoboRTS and RoboRTS-Firmare

### ISSUE THREAD

**Issue by Robin970822** [RoboMaster/RoboRTS#21]
https://github.com/RoboMaster/RoboRTS/blob/98a2ff1e297ba57e51ca46e72892c98a6fb0f99c/modules/driver/serial/infantry_info.h#L421

https://github.com/RoboMaster/RoboRTS-Firmware/blob/f7d21b0c6261718b302435b2961caca097b52e5b/MDK-ARM/rmlib/infantry_info.h#L270

They are different......

**Comment by KevinLADLee** [comment]
Same issue as #20
