### ISSUE TITLE
the sleep() time set in the run_example.sh is too short causing "Get Robot Pose Error"

### ISSUE THREAD

**Issue by yanhaoy** [RoboMaster/RoboRTS#3]
the sleep() time set in the run_example.sh is too short causing "Get Robot Pose Error"

if I run the commands individually, the example can be opened successfully,
but if I run the run_example.sh,i get error.

Yang Yanhao
South China University Of Technology

**Comment by KevinLADLee** [comment]
It is the same as this [issue](https://github.com/RoboMaster/RoboRTS/issues/1), we will fix it.
