### ISSUE TITLE
Some mistake about the course

### ISSUE THREAD

**Issue by QHonthebed** [RoboMaster/RoboRTS#30]
During my study of the DJI RoboRTS, I find some mistake about the Introductory course (https://robomaster.github.io/RoboRTS-Tutorial/#/sdk_docs/architecture).
On the chapter of it's "roborts_base"->"模块介绍",there is a mistake after the Node graph, the first title should be "底盘模块" not the "云台模块"。

**Comment by charmyoung** [comment]
Thanks a lot. We have fix the typos.
