### ISSUE TITLE
amcl 接收初始定位信息时的tf变换

### ISSUE THREAD

**Issue by sweetquiet** [RoboMaster/RoboRTS#36]
您好 链接中odom_frame_是否应该是"/map"呢?https://github.com/RoboMaster/RoboRTS/blob/8d720a1ea0f42895ae7b3d518486f29fe9b7eff6/roborts_localization/localization_node.cpp#L137

**Comment by XinZhangk** [comment]
I think the tf frames are correct as the parent of the base link frame in the tf tree should indeed be odometry. See [here](http://wiki.ros.org/amcl) for more details about the design of localization scheme. Especially the figure in section 3.1.6.

**Comment by sweetquiet** [comment]
@XinZhangk 恩恩 我也发现了ros1 和 ros2 的amcl里初始化里都是odom_frame,因为那时可能还没有global_frame,但是 接下来 odom transform * pose_old 就变成了map下的pose了呢?难道是一个估计吗?
