### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by wangshulei** [RoboMaster/RoboRTS#37]
There some errors when I make the project，like the picture, can you tell me what's wrong? My Tx2 environment is ubuntu 18.04 and ROS melodic.
![微信图片_20190925104101](https://user-images.githubusercontent.com/18264622/65593387-f515b200-dfc2-11e9-8c27-0f8bf26e72a6.jpg)

**Comment by XinZhangk** [comment]
This code base is prepared to run on ubuntu 16 + kinetic. There are a few updates on the syntax of some libraries between kinetic and melodic. You can circumvent the incompatibility by finding the culprits and manually changing them.

**Comment by KevinLADLee** [comment]
Hi, @wangshulei! If your environment is Ubuntu 18.04, you could refer to my [RoboRTS-Edu](https://github.com/Artinx-Robotics/RoboRTS-Edu) project forked from this RoboRTS project. 

I have fixed some dependencies and build errors on Ubuntu 18.04 (Jetson Nano). Hope this will be helpful to you.
