### ISSUE TITLE
can you tell me how to deal with this problem?

### ISSUE THREAD

**Issue by Takki-cd** [RoboMaster/RoboRTS#38]
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
roborts_bringup: Cannot locate rosdep definition for [roborts_tf]

**Comment by Takki-cd** [comment]
can you tell me how to deal with it?

**Comment by XinZhangk** [comment]
With the little information you have provided I can only speculate. But it looks to me that you didn't finish a standard ros installation. Have you run the following commands?
```bash
sudo rosdep init
rosdep update
```

**Comment by KevinLADLee** [comment]
The package [roborts_tf] is deprecated. You could delete it in 'roborts_bringup/package.xml' .

https://github.com/RoboMaster/RoboRTS/blob/ros/roborts_bringup/package.xml#L20

**Comment by Takki-cd** [comment]
thank you, got it------------------ 原始邮件 ------------------
发件人: "KevinLAD"<notifications@github.com>
发送时间: 2019年12月30日(星期一) 凌晨1:39
收件人: "RoboMaster/RoboRTS"<RoboRTS@noreply.github.com>;
抄送: "cd4806088"<1424026564@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [RoboMaster/RoboRTS] can you tell me how to deal with thisproblem? (#38)



The package [roborts_tf] is deprecated. You could delete it in 'roborts_bringup/package.xml' .
 
https://github.com/RoboMaster/RoboRTS/blob/ros/roborts_bringup/package.xml#L20
 
&mdash;
