### ISSUE TITLE
The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by blyspyder** [RoboMaster/RoboRTS#46]
using ubuntu18.04 when I execute catkin_make, I get this error
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLOG_LIBRARY (ADVANCED)
    linked by target "global_planner_node" in directory /home/bly/project/roborts_ws/src/RoboRTS/roborts_planning/global_planner

-- Configuring incomplete, errors occurred!
See also "/home/bly/project/roborts_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/bly/project/roborts_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by charmyoung** [comment]
previous version only support ubuntu16.04 ros kinetic. please try current version with compatibility with ros melodic version.
