### ISSUE TITLE
catkin_make error not found for -lOpenNI

### ISSUE THREAD

**Issue by Lolipop-cloud** [RoboMaster/RoboRTS#48]
Hi,
I was running catkin_make command on manifold 2 and i got the following message:

`
/usr/bin/ld: 当搜索用于 /usr/lib/gcc/aarch64-linux-gnu/5/../../../../lib/libOpenNI.so 时跳过不兼容的 -lOpenNI
/usr/bin/ld: 当搜索用于 /usr/lib/../lib/libOpenNI.so 时跳过不兼容的 -lOpenNI
/usr/bin/ld: 当搜索用于 /usr/lib/gcc/aarch64-linux-gnu/5/../../../libOpenNI.so 时跳过不兼容的 -lOpenNI
/usr/bin/ld: 当搜索用于 //usr/lib/libOpenNI.so 时跳过不兼容的 -lOpenNI
/usr/bin/ld: 找不到 -lOpenNI
collect2: error: ld returned 1 exit status
RoboRTS-ros/roborts_costmap/CMakeFiles/roborts_costmap.dir/build.make:574: recipe for target '/home/dji/roborts_ws/devel/lib/libroborts_costmap.so' failed
make[2]: *** [/home/dji/roborts_ws/devel/lib/libroborts_costmap.so] Error 1
CMakeFiles/Makefile2:4940: recipe for target 'RoboRTS-ros/roborts_costmap/CMakeFiles/roborts_costmap.dir/all' failed
make[1]: *** [RoboRTS-ros/roborts_costmap/CMakeFiles/roborts_costmap.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j6 -l6" failed
`
any ideas ? :(

**Comment by charmyoung** [comment]
please check the openNI dependencies for pcl library.
