### ISSUE TITLE
camera driver 

### ISSUE THREAD

**Issue by joke123kobe** [RoboMaster/RoboRTS#6]
when I tried to run the example, I typed the command ./build/modules/drive/camera/camera_driver, is said that ROS_MASTER_URI is not defined in the environment. But I add export ROS_MASTER_URI=http://localhost:11311 in the  .bashrc file. It doesn't  work,either

**Comment by KevinLADLee** [comment]
If you run example on single PC, please check every steps on the following page.
[ROS Installation Guide](http://wiki.ros.org/kinetic/Installation/Ubuntu)
If on multi computers, please check another page
[ROS Networking Setup](http://wiki.ros.org/Robots/TurtleBot/Network%20Setup)

It is exactly an environment setup problem. Please check you ROS configuration twice.
